### ISSUE TITLE
Обработка информации

### ISSUE THREAD

**Issue by kkkkikkki** [lerfich/smartClinic#4]
- [x] Всем: После просмотра списка Заказчика, определить какие из ФК мы можем рассмотреть. Все сразу не стоит брать

- [x] Аналитику: проанализировать какие подобные сервисы есть, что можно позаимствовать, воссоздать (затем всем вместе это обсудить) 

- [x] Предоставить первые данные заказчику (ПМ)

- Так же желательно обсудить свои наработки с руководителями практики (Блеканов, Севрюков). Если в пн будет встреча, то поднимем этот вопрос.

**Comment by lerfich** [comment]
По первому пункту, размышления такие:
на мой взгляд можем взять следующие:

**1) ФК «Электронная регистратура». Предназначен для ведения общего списка пациентов ЛОКБ и поддержания данных в актуальном состоянии.** 
Почему? Ну очевидно это основополагающий раздел, чтобы пациенты могли регистрироваться/пользоваться услугами, необходимо добавить возможность регистрации и соответствующие блоки

**2) ФК «Электронное расписание». Предназначен для регистрации пациентов, создания расписания и управления записью на прием к врачу и в диагностические кабинеты** 
Почему? В полной мере реализовать это будет сложно, не хватит рук. Здесь нужно поддерживать: доступ к расписанию, кому отправлять расписание, кому менять, кого оповещать, понятие “кабинетов” и времени посещения. Это очень большая задача, думаю реалистично реализовать общее расписание, которое можно просматривать и создавать через простенькое меню

**4) ФК «Врач». Предназначен для ведения медицинской документации на амбулаторном этапе, в диагностических и стационарных отделениях.** 
Почему? Если правильно понимаю, это личный кабинет врача, в котором он может дополнять информацию о пациенте, который к нему приходил, таким образом появляется история любого пациента. На базовом уровне реализовать можно, но ЛК врача и пациента будут похожи (переиспользуемы)

**6) ФК «Редактор услуг». Предназначен для автоматизации и информационного обеспечения учета себестоимости медицинских услуг.** 
Почему? Здесь необходимо будет реализовать понятие сущности “услуга” у нее будет описание, стоимость и принадлежность к пациенту/врачу, в случае выбора. На базовом уровне можно реализовать

**9) ФК «Приемное отделение». Предназначен для оформления госпитализаций пациентов в отделения дневного и круглосуточного стационара ЛОКБ**  
Почему? Если здесь имеется в виду возможность выбора оформления в одно из двух стационаров для госпитализации, то выглядит как реализуемая задача, но на базовом уровне в четыре шага: выбор госпитализации - формата госпитализации - дня госпитализации - отображение в ЛК пациента

**11) ФК «Планирование госпитализаций». Предназначен для учета планирования госпитализаций в стационарные отделения на амбулаторном этапе** 
Почему? Выглядит как логичное дополнение к 9) ФК, только для врачей, задействованных в госпитализации

**12) ФК «Платные услуги». Предназначен для регистрации случаев оказания медицинской помощи за счет собственных средств и средств СМК за пациентов, имеющих полис ДМС и формирования реестров счетов, аналитической и финансовой отчетности по работе отделения** 
Почему? Это большой блок, но его можно сделать в базовом виде: возможно выбора раздела “платные услуги”, который будет иметь услуги аналогичные обычным (переиспользуемый компонент), но с необходимым вводом номера полиса для записи. В остальном - обычная услуга


**14) ФК «Реанимация». Предназначен для ведения медицинской документации в истории болезни пациентов реанимации.** 
Почему? Если реализовать как небольшой раздел в ЛК для пациента/врача в случае реанимации пациента с описанием истории, реализуемая задача

Функциональные компоненты МИС, которые не пойдут в реализацию:

**3) ФК «Администратор отделения инструментальной диагностики». Предназначен для автоматизации процессов согласования диагностических исследований для пациентов.**  
Непонятный раздел, слишком мало конкретики, выглядит как большая задача

**5) ФК «Стационарные отделения (Медицинская сестра)». Предназначен для автоматизации и информационного обеспечения деятельности по оказанию стационарной помощи пациентам от госпитализации до выписки с учётом специфики работы медицинской сестры в Системе.** 
Непонятный раздел, слишком мало конкретики, выглядит как большая задача

**7) ФК «Интеграция». Предназначен для настройки интерфейсов взаимодействия с внутренними системами ЛОКБ  и внешними системами Ленинградской области.** 
Размытое описание, очень большая задача

**8) ФК «Администрирование системы». Предназначен для настройки Системы под индивидуальные нужды ЛОКБ, а также для учета ресурсов ЛОКБ – сотрудников, оборудования и помещений – в объеме, необходимом для управления их занятостью.** 
Очень большой раздел, задачи по “индивидуализации системы” и “учета ресурсов ЛОКБ” вообще было бы правильно разделить, но даже в этом случае задачи остаются большими и малопонятными

**10) ФК «Операционный блок». Предназначен для планирования проведения плановых и экстренных операций, учёта работы операционных залов и оборудования в них.** 
Очень большой раздел, должен быть доступен только для врачей и выглядит как отдельная система

**13) ФК «ТФОМС». Предназначен для формирования и выставления реестров счетов в ТФОМС ЛО по итогам лечения пациентов в ЛОКБ** 
Большой раздел, который полностью завязан на статусе выполнения услуги, а также стоимости, различных форматов счетов
